<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SenPri" failures="2" tests="18" name="Default test" time="40.397" errors="0" timestamp="2023-05-21T11:38:24 EDT">
  <testcase classname="com.testcase.HomepageTest" name="linkisClickable" time="0.473"/>
  <testcase classname="com.testcase.HomepageTest" name="clicklinkstest" time="5.496"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest" time="12.305"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest" time="2.016"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest" time="1.935"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest" time="1.913"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest" time="1.907"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForUserName" time="0.638"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForUserName" time="0.636"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForUserName" time="0.502"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForUserName" time="0.622"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForUserName" time="0.705"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForPassword" time="0.48"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForPassword" time="1.125">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Testing_if_the_Null_value_for_Password_in_HomePage_will_be_ACCEPETED expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Testing_if_the_Null_value_for_Password_in_HomePage_will_be_ACCEPETED expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.testcase.HomepageTest.logintest_NullDataForPassword(HomepageTest.java:112)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logintest_NullDataForPassword -->
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForPassword" time="0.605"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForPassword" time="0.615"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForPassword" time="0.669"/>
  <testcase classname="com.testcase.HomepageTest" name="logintest_NullDataForUserName_and_Password" time="0.758">
    <failure type="java.lang.AssertionError" message="Testing whether username and password in Home Page accepts null values expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Testing whether username and password in Home Page accepts null values expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at com.testcase.HomepageTest.logintest_NullDataForUserName_and_Password(HomepageTest.java:122)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logintest_NullDataForUserName_and_Password -->
</testsuite> <!-- Default test -->
