<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SenPri" failures="1" tests="9" name="com.testcase.RegisterTest" time="7.848" errors="0" timestamp="2023-05-21T10:45:50 EDT" skipped="0">
  <testcase classname="com.testcase.RegisterTest" name="entercontactdetails" time="0.778"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="entercontactdetails" time="0.556"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="entermailingdetails" time="0.449"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="entermailingdetails" time="0.522"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="enteruserdetails" time="0.248"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="enteruserdetails" time="0.215"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="registrationtest" time="1.902"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="registrationtest" time="1.697"/>
  <system-out/>
  <testcase classname="com.testcase.RegisterTest" name="registrationtest_Null_Data" time="1.481">
    <failure message="Testing whether the regitstration datas accepts null values expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testing whether the regitstration datas accepts null values expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at com.testcase.RegisterTest.registrationtest_Null_Data(RegisterTest.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- registrationtest_Null_Data -->
  <system-out/>
</testsuite> <!-- com.testcase.RegisterTest -->
